# Generated by Django 4.0.4 on 2022-06-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='fecha',
        ),
    ]
