# Generated by Django 4.0.4 on 2022-06-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0002_remove_comentario_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='telefono',
        ),
    ]
