# Generated by Django 4.0.4 on 2022-06-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0003_remove_comentario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='email',
        ),
    ]
